services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    image: temur-portfolio:local
    container_name: temur-portfolio
    ports:
      - '8080:80'
    restart: unless-stopped
